# Generated by Django 6.0.5 on 2026-05-21 12:08

import django.utils.timezone
import pharmacy.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_additionalservice_pickuppoint_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='purchased_at',
            field=models.DateTimeField(default=django.utils.timezone.now, validators=[pharmacy.validators.validate_not_future_datetime], verbose_name='Дата покупки'),
        ),
    ]
