# Generated by Django 6.0.5 on 2026-09-14 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_alter_purchase_purchased_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название')),
                ('website_url', models.URLField(verbose_name='Сайт компании')),
                ('logo_url', models.URLField(blank=True, verbose_name='Ссылка на логотип')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Краткое описание')),
            ],
            options={
                'verbose_name': 'Компания-партнёр',
                'verbose_name_plural': 'Компании-партнёры',
                'ordering': ['name'],
            },
        ),
    ]
